name: pardeep-infra-pipeline

on: workflow_dispatch
jobs:
  Buildjob:
    name: agent
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: latest 
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
          
  
  
   

  
